source 'https://rubygems.org'

gem 'rake', '~> 13.0'
gem 'rake_circle_ci', '~> 0.9'
gem 'rake_github', '~> 0.9'
gem 'rake_ssh', '~> 0.4'
gem 'rake_gpg', '~> 0.12'
gem 'confidante', '~> 0.21'
gem 'git', '~> 1.7'
gem 'semantic', '~> 1.6'
